version: 0.2
proxy:
    upload-artifacts: yes
    logs: yes
phases:
    install:
        runtime-versions:
            python: 3.8
    pre_build: 
        commands:
            - echo do nothing
    build:
        commands:
            - echo Starting test Proper Tagging
            - echo Create a new VM with corrcet set of tags
            - aws ec2 create-key-pair --key-name MyKeyPair --query ''KeyMaterial'' --output text > MyKeyPair.pem
            - chmod 400 MyKeyPair.pem
    post_build:
        commands:
            - echo Build completed on `date`
        finally: null
artifacts:
    files:
        - target/messageUtil-1.0.jar
